"""empty message

Revision ID: 9d6bc1921cb0
Revises: 
Create Date: 2021-06-25 12:46:50.748620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d6bc1921cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('polarity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subjectivity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('favorite_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retweet_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_author', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friends_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('possibly_sensitive', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('user_mentions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    # ### end Alembic commands ###
